### ISSUE TITLE
Suggestion: [[fallthrough]]

### ISSUE THREAD

**Issue by mugurelenache** [SasLuca/LCLCompiler#1]
Line 30: LCLCompiler/sources/tokenizer.cpp

Use ```[[fallthrough]]``` attribute in the switch to suppress the warnings generated by the compiler for the empty cases.

**Comment by SasLuca** [comment]
Actually, as per cppreference.com example, this isn't actually a case where you have to use `[[fallthrough]]`.

Subsequent empty cases that signify that the same block of code should execute for all the enumerated cases don't require `[[fallthrough]]`, this should also be evident by the fact that the compiler doesn't warn about fallthrough in that code.

See the example here: https://en.cppreference.com/w/cpp/language/attributes/fallthrough
